services:
  server:
    build: ./server

    ports:
      - "5000:5000"

    volumes:
      - ./server:/server
      - zenai_server_node_modules:/server/node_modules

    env_file:
      - ./server/.env

    command: npm run dev

  client:
    build: ./client

    ports:
      - "5173:5173"

    volumes:
      - ./client:/client
      - zenai_client_node_modules:/client/node_modules

    env_file:
      - ./client/.env

    command: npm run dev

volumes:
  zenai_server_node_modules:
  zenai_client_node_modules: